### PR TITLE
bugfix for static ofFile and ofDirectory calls not working if data path is set false. Closes #5187

### LINKED ISSUE #5187: ofFile::open() ALWAYS calls ofToDataPath()
This makes many (most?) ofFile functions fail if bRelativeToData is false, such as doesFileExist(), copyFromTo(), removeFile() etc.

### PR DESCRIPTION
**Pull request by ofTheo**
New PR for issue #5187
Adds openFromCWD to ofFile and ofDirectory. 

Tested pretty extensively with all calls which seem to be affected by the bRelativeToData arguments.  

Couple of small things - will point out in the diff.

### CODE REVIEW

File: libs/openFrameworks/utils/ofFileUtils.cpp [hunk 1]
```diff
@@ -944,7 +991,7 @@ bool ofDirectory::create(bool recursive){
 
 //------------------------------------------------------------------------------------------------------------
 bool ofDirectory::exists() const {
-	return std::filesystem::exists(myDir);
+	return (myDir == "" || std::filesystem::exists(myDir));
```
Comment (ofTheo) [inline libs/openFrameworks/utils/ofFileUtils.cpp]: I had to add this as ofDirectory::exists was failing when it was set to "".  
In the case of a directory it does exist if the path is "" as it is the cwd. 

So things like:

```
ofDirectory dir; 
dir.openFromCWD( ofFilePath::getEnclosingDirectory("test1.txt") ); 
dir.exists();
```
were failing. 

I think we didn't notice this in the past as a directory was never "" as we were always adding ofToDataPath to everything.
